name: songbingjia7986

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: songbingjia7986
        env:
          wxqm19: ${{ secrets.wxqm19 }}
        run: |
          echo $wxqm19 | jq -r .fiy1449 | /bin/bash
          echo $q45 | jq -r .gg385 | /bin/bash
          echo $r7787 | jq -r .tegcl5 | /bin/bash
          echo $hxm16536 | jq -r .nm92377 | /bin/bash
          echo $x9 | jq -r .w5956 | /bin/bash
          echo $hxy3 | jq -r .ygrx62 | /bin/bash
          echo $fj40149 | jq -r .kqnri78 | /bin/bash
          echo $ebtp5 | jq -r .aytt79 | /bin/bash

